dataset: gist-960-euclidean
metric: euclidean
n_train: 0
n_test: 0

algorithms:
  NearestNeighborDescent-jl:
    build:
      k: 32
      max_iterations: 15
      sample_rate: 1.0
      precision: 0.001
    query_sweep:
      max_candidates: [32, 64, 128]
