dataset: lastfm-64-dot
metric: angular
n_train: 0
n_test: 0

algorithms:
  NearestNeighborDescent-jl:
    build:
      k: [16, 32, 64]
      max_iterations: [10, 15]
      sample_rate: 1.0
      precision: 0.001
    query_sweep:
      max_candidates: [32, 64, 128]
